obj-y += mt_spm_mtcmos.o
obj-y += mt_clkmgr_common.o
obj-y += mt_clkmgr.o
obj-y += mt_golden_setting.o
obj-y += mt_clkbuf_ctl.o
obj-y += mt_pm_init.o
obj-y += mt_spm.o
obj-y += mt_spm_internal.o
obj-y += mt_cpufreq.o
obj-y += mt_gpufreq.o
obj-y += mt_ptp.o
obj-y += mt_dcm.o

obj-y += mt-smp.o
obj-y += hotplug.o
obj-y += mt-headsmp.o
obj-y += mt_hotplug.o
